[DOCUMENTATION]
ORG_NAME="klaylumen Inc."
ORG_URL="http://klaylm.xyz"
ORG_LOGO="http://klaylm.xyz/klaylm.png"
ORG_DESCRIPTION="Greentheplatform Company based on Singapore"

[[CURRENCIES]]
code="klayLM"
issuer="GBHMMXI2IMAYVYYRJPPYRQBQQP3OKHHNUHVT2GZ6273MDU2GEKRZWZ7L"
display_decimals=7
image="http://klaylm.xyz/klaylm.png"
name="klaylumen"
desc="BUY ONLY, NO SELL, UNTIL GAZUA"
fixed_number = 999999999
conditions="hot"
status="live"
